# Generated by Django 2.2.1 on 2019-06-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Month')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('licence', models.CharField(max_length=100, verbose_name='Licence ID')),
                ('employee_management', models.PositiveSmallIntegerField(verbose_name='Management Employees')),
                ('employee_administrative', models.PositiveSmallIntegerField(verbose_name='Administrative Employees')),
                ('employee_production', models.PositiveSmallIntegerField(verbose_name='Production Employees')),
                ('employee_sales', models.PositiveSmallIntegerField(verbose_name='Sales Employees')),
                ('employee_other', models.PositiveSmallIntegerField(verbose_name='Other Employees')),
                ('capacity_flowering_area', models.PositiveSmallIntegerField(verbose_name='Flowering Area Utilized Capacity')),
                ('capacity_mother_room', models.PositiveSmallIntegerField(verbose_name='Mother Room Capacity')),
                ('capacity_cloning_room', models.PositiveSmallIntegerField(verbose_name='Cloning Room Capacity')),
                ('capacity_drying_room', models.PositiveSmallIntegerField(verbose_name='Drying Room Capacity')),
            ],
            options={
                'verbose_name_plural': 'Business',
            },
        ),
        migrations.CreateModel(
            name='Inventory_Finished',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Month')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('licence', models.CharField(max_length=100, verbose_name='Licence ID')),
                ('product', models.CharField(max_length=100, verbose_name='Product Type')),
                ('opening_inventory', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Opening Inventory')),
                ('addition_packaged', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Packaged')),
                ('addition_purchased', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Purchased/Transferred')),
                ('addition_returned', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Returned')),
                ('addition_other', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Additions Other')),
                ('reduction_sold', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Sold/Transferred')),
                ('reduction_destroyed', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Destroyed')),
                ('reduction_stolen', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Lost/Stolen')),
                ('reduction_returned', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Returned')),
                ('reduction_other', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Other Reductions')),
            ],
            options={
                'verbose_name_plural': 'Finished Inventory',
            },
        ),
        migrations.CreateModel(
            name='Inventory_Unfinished',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Month')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('licence', models.CharField(max_length=100, verbose_name='Licence ID')),
                ('product', models.CharField(max_length=100, verbose_name='Product Type')),
                ('opening_inventory', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Opening Inventory')),
                ('addition_total_production', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Total Production')),
                ('addition_purchased_cultivator', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Purchased/Transferred from Cultivators')),
                ('addition_purchased_processor', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Purchased/Transferred from Processors')),
                ('addition_purchased_hemp', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Purchased/Transferred from Hemp')),
                ('addition_purchased_tester', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Purchased/Transferred from Testers or Researchers')),
                ('addition_imported', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Imported into Canada')),
                ('addition_returned', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Returned')),
                ('reduction_processed', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Processed')),
                ('reduction_packaged', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Packaged and Labeled')),
                ('reduction_sold_cultivator', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Sold/Transferred to Cultivators')),
                ('reduction_sold_processor', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Sold/Transferred to Processors')),
                ('reduction_sold_hemp', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Sold/Transferred to Hemp')),
                ('reduction_sold_tester', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Sold/Transferred to Testers or Researchers')),
                ('reduction_exported', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Exported Outside Canada')),
                ('reduction_drying_loss', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Adjustment for Drying/Processing Loss')),
                ('reduction_destroyed', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Destroyed')),
                ('reduction_stolen', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Lost/Stolen')),
                ('reduction_returned', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity Returned')),
                ('reduction_other', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Other Reductions')),
            ],
            options={
                'verbose_name_plural': 'Unfinished Inventory',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('location_abbr', models.CharField(max_length=2, verbose_name='Province Abbreviation')),
                ('location', models.CharField(max_length=50, verbose_name='Province')),
            ],
            options={
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('period_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField(verbose_name='Month')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
            ],
            options={
                'verbose_name_plural': 'Period',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=100, verbose_name='Product Type')),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Month')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('licence', models.CharField(max_length=100, verbose_name='Licence ID')),
                ('location', models.PositiveSmallIntegerField(verbose_name='Province')),
                ('product', models.CharField(max_length=100, verbose_name='Product Type')),
                ('consumption', models.CharField(max_length=100, verbose_name='Consumption Type')),
                ('distribution', models.CharField(max_length=100, verbose_name='Distribution Type')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantity')),
            ],
            options={
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
