# Generated by Django 2.2.1 on 2019-06-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='capacity_cloning_room',
            field=models.PositiveIntegerField(verbose_name='Cloning Room Capacity'),
        ),
        migrations.AlterField(
            model_name='business',
            name='capacity_drying_room',
            field=models.PositiveIntegerField(verbose_name='Drying Room Capacity'),
        ),
        migrations.AlterField(
            model_name='business',
            name='capacity_flowering_area',
            field=models.PositiveIntegerField(verbose_name='Flowering Area Utilized Capacity'),
        ),
        migrations.AlterField(
            model_name='business',
            name='capacity_mother_room',
            field=models.PositiveIntegerField(verbose_name='Mother Room Capacity'),
        ),
    ]
