# Generated by Django 2.2.1 on 2019-06-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctsapp', '0002_auto_20190601_1023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory_Finished',
            new_name='InventoryFinished',
        ),
        migrations.RenameModel(
            old_name='Inventory_Unfinished',
            new_name='InventoryUnfinished',
        ),
    ]
