# Generated by Django 2.2.1 on 2019-06-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctsapp', '0003_auto_20190602_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='location',
            field=models.CharField(max_length=25, verbose_name='Province'),
        ),
    ]
